/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 Receive Data Source Select: UART_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 Transmit Data Source Select: UART0_TX pin */
#define SOPT5_UART1RXSRC_UART_RX 0x00u /*!<@brief UART1 Receive Data Source Select: UART1_RX pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART1 Transmit Data Source Select: UART1_TX pin */

/*! @name PORTC3 (number 46), LED1_R
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED1_R_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED1_R_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED1_R_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED1_R_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED1_R_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_LED1_R_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTC4 (number 49), LED1_G
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED1_G_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED1_G_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED1_G_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED1_G_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED1_G_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_LED1_G_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTC5 (number 50), LED1_B
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED1_B_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED1_B_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED1_B_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED1_B_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED1_B_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_LED1_B_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTC0 (number 43), LED2_G
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED2_G_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED2_G_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED2_G_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED2_G_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED2_G_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_LED2_G_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTC2 (number 45), LED2_B
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED2_B_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED2_B_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED2_B_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED2_B_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED2_B_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_LED2_B_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTB19 (number 42), LED2_R
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED2_R_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED2_R_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED2_R_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED2_R_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_LED2_R_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_LED2_R_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTB16 (number 39), LED3_R
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED3_R_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED3_R_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED3_R_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED3_R_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_LED3_R_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_LED3_R_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTB17 (number 40), LED3_G
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED3_G_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED3_G_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED3_G_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED3_G_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_LED3_G_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_LED3_G_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTB18 (number 41), LED3_B
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED3_B_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LED3_B_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED3_B_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED3_B_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_LED3_B_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_LED3_B_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTB3 (number 38), LCD_RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LCD_RST_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LCD_RST_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LCD_RST_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LCD_RST_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD_RST_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_LCD_RST_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTB2 (number 37), LCD_DC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LCD_DC_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LCD_DC_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LCD_DC_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LCD_DC_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD_DC_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_LCD_DC_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTC6 (number 51), SW1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW1_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SW1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW1_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_SW1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTC7 (number 52), SW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW2_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SW2_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW2_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW2_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_SW2_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTC8 (number 53), SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW3_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SW3_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW3_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW3_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_SW3_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTC9 (number 54), SW4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW4_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SW4_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW4_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW4_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW4_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_SW4_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTA5 (number 27), SW5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW5_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SW5_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW5_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW5_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW5_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_SW5_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTA12 (number 28), SW6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW6_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SW6_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW6_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW6_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_SW6_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_SW6_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTA13 (number 29), SW7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW7_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SW7_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW7_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW7_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_SW7_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_SW7_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTA19 (number 33), SW8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW8_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SW8_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW8_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW8_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_SW8_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_SW8_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTE20 (number 9), AD5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_AD5_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_AD5_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_AD5_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_AD5_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_AD5_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_AD5_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTE22 (number 11), AD3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_AD3_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_AD3_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_AD3_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_AD3_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_AD3_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_AD3_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTE23 (number 12), AD2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_AD2_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_AD2_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_AD2_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_AD2_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_AD2_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_AD2_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTE29 (number 17), AD1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_AD1_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_AD1_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_AD1_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_AD1_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_AD1_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_AD1_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTE30 (number 18), AD0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_AD0_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_AD0_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_AD0_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_AD0_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_AD0_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_AD0_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTE31 (number 19), IO12
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO12_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO12_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO12_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO12_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_IO12_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_IO12_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTE24 (number 20), IO10
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO10_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO10_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO10_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO10_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_IO10_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_IO10_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTE25 (number 21), IO11
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO11_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO11_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO11_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO11_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_IO11_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_IO11_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTD0 (number 57), IO7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO7_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO7_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO7_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO7_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_IO7_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_IO7_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTD1 (number 58), IO6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO6_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO6_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO6_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO6_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_IO6_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_IO6_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTD2 (number 59), IO5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO5_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO5_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO5_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO5_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_IO5_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_IO5_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTD3 (number 60), IO4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO4_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO4_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO4_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO4_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_IO4_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_IO4_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTD4 (number 61), IO3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO3_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO3_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO3_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO3_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_IO3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_IO3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTD5 (number 62), IO2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO2_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO2_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO2_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_IO2_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_IO2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTD6 (number 63), IO1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO1_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO1_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO1_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_IO1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_IO1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTD7 (number 64), IO0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO0_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO0_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO0_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO0_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_IO0_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_IO0_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTC10 (number 55), IO8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO8_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO8_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO8_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO8_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_IO8_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_IO8_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTC11 (number 56), IO9
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_IO9_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_IO9_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_IO9_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_IO9_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_IO9_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_IO9_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTE21 (number 10), AD4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_AD4_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_AD4_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_AD4_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_AD4_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_AD4_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_AD4_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTB0 (number 35), LCD_D1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LCD_D1_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LCD_D1_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LCD_D1_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LCD_D1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD_D1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_LCD_D1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTB1 (number 36), LCD_D0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LCD_D0_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_LCD_D0_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LCD_D0_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LCD_D0_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD_D0_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LCD_D0_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
