/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MKL26Z256xxx4
package_id: MKL26Z256VLH4
mcu_data: ksdk2_0
processor_version: 8.0.1
pin_labels:
- {pin_num: '33', pin_signal: XTAL0/PTA19/UART1_TX/TPM_CLKIN1/LPTMR0_ALT1, label: SW8, identifier: SW8}
- {pin_num: '29', pin_signal: PTA13/TPM1_CH1/I2S0_TX_FS, label: SW7, identifier: SW7}
- {pin_num: '28', pin_signal: PTA12/TPM1_CH0/I2S0_TXD0, label: SW6, identifier: SW6}
- {pin_num: '27', pin_signal: PTA5/USB_CLKIN/TPM0_CH2/I2S0_TX_BCLK, label: SW5, identifier: SW5}
- {pin_num: '54', pin_signal: CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5/I2S0_RX_BCLK, label: SW4, identifier: SW4}
- {pin_num: '53', pin_signal: CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4/I2S0_MCLK, label: SW3, identifier: SW3}
- {pin_num: '52', pin_signal: CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/I2S0_RX_FS/SPI0_MOSI, label: SW2, identifier: SW2}
- {pin_num: '51', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK, label: SW1, identifier: SW1}
- {pin_num: '37', pin_signal: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/TPM2_CH0, label: LCD_DC, identifier: LCD_DC}
- {pin_num: '35', pin_signal: ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0, label: LCD_D1, identifier: LCD_D1}
- {pin_num: '36', pin_signal: ADC0_SE9/TSI0_CH6/PTB1/I2C0_SDA/TPM1_CH1, label: LCD_D0, identifier: LCD_D0}
- {pin_num: '38', pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/TPM2_CH1, label: LCD_RST, identifier: LCD_RST}
- {pin_num: '41', pin_signal: TSI0_CH11/PTB18/TPM2_CH0/I2S0_TX_BCLK, label: LED3_B, identifier: LED3_B}
- {pin_num: '40', pin_signal: TSI0_CH10/PTB17/SPI1_MISO/UART0_TX/TPM_CLKIN1/SPI1_MOSI, label: LED3_G, identifier: LED3_G}
- {pin_num: '39', pin_signal: TSI0_CH9/PTB16/SPI1_MOSI/UART0_RX/TPM_CLKIN0/SPI1_MISO, label: LED3_R, identifier: LED3_R}
- {pin_num: '42', pin_signal: TSI0_CH12/PTB19/TPM2_CH1/I2S0_TX_FS, label: LED2_R, identifier: LED2_R}
- {pin_num: '45', pin_signal: ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS, label: LED2_B, identifier: LED2_B}
- {pin_num: '43', pin_signal: ADC0_SE14/TSI0_CH13/PTC0/EXTRG_IN/USB_SOF_OUT/CMP0_OUT/I2S0_TXD0, label: LED2_G, identifier: LED2_G}
- {pin_num: '50', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/CMP0_OUT, label: LED1_B, identifier: LED1_B}
- {pin_num: '49', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3/I2S0_MCLK, label: LED1_G, identifier: LED1_G}
- {pin_num: '46', pin_signal: PTC3/LLWU_P7/UART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK, label: LED1_R, identifier: LED1_R}
- {pin_num: '9', pin_signal: ADC0_DP0/ADC0_SE0/PTE20/TPM1_CH0/UART0_TX, label: AD5, identifier: AD5}
- {pin_num: '10', pin_signal: ADC0_DM0/ADC0_SE4a/PTE21/TPM1_CH1/UART0_RX, label: AD4, identifier: AD4}
- {pin_num: '11', pin_signal: ADC0_DP3/ADC0_SE3/PTE22/TPM2_CH0/UART2_TX, label: AD3, identifier: AD3}
- {pin_num: '12', pin_signal: ADC0_DM3/ADC0_SE7a/PTE23/TPM2_CH1/UART2_RX, label: AD2, identifier: AD2}
- {pin_num: '17', pin_signal: CMP0_IN5/ADC0_SE4b/PTE29/TPM0_CH2/TPM_CLKIN0, label: AD1, identifier: AD1}
- {pin_num: '18', pin_signal: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1, label: AD0, identifier: AD0}
- {pin_num: '19', pin_signal: PTE31/TPM0_CH4, label: IO12, identifier: IO12}
- {pin_num: '20', pin_signal: PTE24/TPM0_CH0/I2C0_SCL, label: IO10, identifier: IO10}
- {pin_num: '21', pin_signal: PTE25/TPM0_CH1/I2C0_SDA, label: IO11, identifier: IO11}
- {pin_num: '57', pin_signal: PTD0/SPI0_PCS0/TPM0_CH0, label: IO7, identifier: IO7}
- {pin_num: '58', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1, label: IO6, identifier: IO6}
- {pin_num: '59', pin_signal: PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO, label: IO5, identifier: IO5}
- {pin_num: '60', pin_signal: PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI, label: IO4, identifier: IO4}
- {pin_num: '61', pin_signal: PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4, label: IO3, identifier: IO3}
- {pin_num: '62', pin_signal: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5, label: IO2, identifier: IO2}
- {pin_num: '63', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/UART0_RX/SPI1_MISO, label: IO1, identifier: IO1}
- {pin_num: '64', pin_signal: PTD7/SPI1_MISO/UART0_TX/SPI1_MOSI, label: IO0, identifier: IO0}
- {pin_num: '55', pin_signal: PTC10/I2C1_SCL/I2S0_RX_FS, label: IO8, identifier: IO8}
- {pin_num: '56', pin_signal: PTC11/I2C1_SDA/I2S0_RXD0, label: IO9, identifier: IO9}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: UART1, signal: TX, pin_signal: PTE0/SPI1_MISO/UART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA}
  - {pin_num: '2', peripheral: UART1, signal: RX, pin_signal: PTE1/SPI1_MOSI/UART1_RX/SPI1_MISO/I2C1_SCL}
  - {pin_num: '46', peripheral: GPIOC, signal: 'GPIO, 3', pin_signal: PTC3/LLWU_P7/UART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK, direction: OUTPUT}
  - {pin_num: '49', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3/I2S0_MCLK, direction: OUTPUT}
  - {pin_num: '50', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/CMP0_OUT, direction: OUTPUT}
  - {pin_num: '43', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: ADC0_SE14/TSI0_CH13/PTC0/EXTRG_IN/USB_SOF_OUT/CMP0_OUT/I2S0_TXD0, direction: OUTPUT}
  - {pin_num: '45', peripheral: GPIOC, signal: 'GPIO, 2', pin_signal: ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS, direction: OUTPUT}
  - {pin_num: '42', peripheral: GPIOB, signal: 'GPIO, 19', pin_signal: TSI0_CH12/PTB19/TPM2_CH1/I2S0_TX_FS, direction: OUTPUT}
  - {pin_num: '39', peripheral: GPIOB, signal: 'GPIO, 16', pin_signal: TSI0_CH9/PTB16/SPI1_MOSI/UART0_RX/TPM_CLKIN0/SPI1_MISO, direction: OUTPUT}
  - {pin_num: '40', peripheral: GPIOB, signal: 'GPIO, 17', pin_signal: TSI0_CH10/PTB17/SPI1_MISO/UART0_TX/TPM_CLKIN1/SPI1_MOSI, direction: OUTPUT}
  - {pin_num: '41', peripheral: GPIOB, signal: 'GPIO, 18', pin_signal: TSI0_CH11/PTB18/TPM2_CH0/I2S0_TX_BCLK, direction: OUTPUT}
  - {pin_num: '38', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/TPM2_CH1, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '37', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/TPM2_CH0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '51', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK, direction: INPUT,
    gpio_interrupt: kPORT_InterruptRisingEdge}
  - {pin_num: '52', peripheral: GPIOC, signal: 'GPIO, 7', pin_signal: CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/I2S0_RX_FS/SPI0_MOSI, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge}
  - {pin_num: '53', peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4/I2S0_MCLK, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge}
  - {pin_num: '54', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5/I2S0_RX_BCLK, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge}
  - {pin_num: '27', peripheral: GPIOA, signal: 'GPIO, 5', pin_signal: PTA5/USB_CLKIN/TPM0_CH2/I2S0_TX_BCLK, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge}
  - {pin_num: '28', peripheral: GPIOA, signal: 'GPIO, 12', pin_signal: PTA12/TPM1_CH0/I2S0_TXD0, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge}
  - {pin_num: '29', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: PTA13/TPM1_CH1/I2S0_TX_FS, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge}
  - {pin_num: '33', peripheral: GPIOA, signal: 'GPIO, 19', pin_signal: XTAL0/PTA19/UART1_TX/TPM_CLKIN1/LPTMR0_ALT1, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge}
  - {pin_num: '9', peripheral: GPIOE, signal: 'GPIO, 20', pin_signal: ADC0_DP0/ADC0_SE0/PTE20/TPM1_CH0/UART0_TX}
  - {pin_num: '11', peripheral: GPIOE, signal: 'GPIO, 22', pin_signal: ADC0_DP3/ADC0_SE3/PTE22/TPM2_CH0/UART2_TX}
  - {pin_num: '12', peripheral: GPIOE, signal: 'GPIO, 23', pin_signal: ADC0_DM3/ADC0_SE7a/PTE23/TPM2_CH1/UART2_RX}
  - {pin_num: '17', peripheral: GPIOE, signal: 'GPIO, 29', pin_signal: CMP0_IN5/ADC0_SE4b/PTE29/TPM0_CH2/TPM_CLKIN0}
  - {pin_num: '18', peripheral: GPIOE, signal: 'GPIO, 30', pin_signal: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1}
  - {pin_num: '19', peripheral: GPIOE, signal: 'GPIO, 31', pin_signal: PTE31/TPM0_CH4}
  - {pin_num: '20', peripheral: GPIOE, signal: 'GPIO, 24', pin_signal: PTE24/TPM0_CH0/I2C0_SCL}
  - {pin_num: '21', peripheral: GPIOE, signal: 'GPIO, 25', pin_signal: PTE25/TPM0_CH1/I2C0_SDA}
  - {pin_num: '57', peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: PTD0/SPI0_PCS0/TPM0_CH0}
  - {pin_num: '58', peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1}
  - {pin_num: '59', peripheral: GPIOD, signal: 'GPIO, 2', pin_signal: PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO}
  - {pin_num: '60', peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI}
  - {pin_num: '61', peripheral: GPIOD, signal: 'GPIO, 4', pin_signal: PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4}
  - {pin_num: '62', peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5}
  - {pin_num: '63', peripheral: GPIOD, signal: 'GPIO, 6', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/UART0_RX/SPI1_MISO}
  - {pin_num: '64', peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/SPI1_MISO/UART0_TX/SPI1_MOSI}
  - {pin_num: '55', peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: PTC10/I2C1_SCL/I2S0_RX_FS}
  - {pin_num: '56', peripheral: GPIOC, signal: 'GPIO, 11', pin_signal: PTC11/I2C1_SDA/I2S0_RXD0}
  - {pin_num: '10', peripheral: GPIOE, signal: 'GPIO, 21', pin_signal: ADC0_DM0/ADC0_SE4a/PTE21/TPM1_CH1/UART0_RX}
  - {pin_num: '24', peripheral: UART0, signal: TX, pin_signal: TSI0_CH3/PTA2/UART0_TX/TPM2_CH1}
  - {pin_num: '23', peripheral: UART0, signal: RX, pin_signal: TSI0_CH2/PTA1/UART0_RX/TPM2_CH0}
  - {pin_num: '35', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0, direction: OUTPUT}
  - {pin_num: '36', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE9/TSI0_CH6/PTB1/I2C0_SDA/TPM1_CH1, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t SW5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA5 (pin 27)  */
    GPIO_PinInit(BOARD_SW5_GPIO, BOARD_SW5_PIN, &SW5_config);

    gpio_pin_config_t SW6_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA12 (pin 28)  */
    GPIO_PinInit(BOARD_SW6_GPIO, BOARD_SW6_PIN, &SW6_config);

    gpio_pin_config_t SW7_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA13 (pin 29)  */
    GPIO_PinInit(BOARD_SW7_GPIO, BOARD_SW7_PIN, &SW7_config);

    gpio_pin_config_t SW8_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA19 (pin 33)  */
    GPIO_PinInit(BOARD_SW8_GPIO, BOARD_SW8_PIN, &SW8_config);

    gpio_pin_config_t LCD_D1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 35)  */
    GPIO_PinInit(BOARD_LCD_D1_GPIO, BOARD_LCD_D1_PIN, &LCD_D1_config);

    gpio_pin_config_t LCD_D0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 36)  */
    GPIO_PinInit(BOARD_LCD_D0_GPIO, BOARD_LCD_D0_PIN, &LCD_D0_config);

    gpio_pin_config_t LCD_DC_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 37)  */
    GPIO_PinInit(BOARD_LCD_DC_GPIO, BOARD_LCD_DC_PIN, &LCD_DC_config);

    gpio_pin_config_t LCD_RST_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 38)  */
    GPIO_PinInit(BOARD_LCD_RST_GPIO, BOARD_LCD_RST_PIN, &LCD_RST_config);

    gpio_pin_config_t LED3_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB16 (pin 39)  */
    GPIO_PinInit(BOARD_LED3_R_GPIO, BOARD_LED3_R_PIN, &LED3_R_config);

    gpio_pin_config_t LED3_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB17 (pin 40)  */
    GPIO_PinInit(BOARD_LED3_G_GPIO, BOARD_LED3_G_PIN, &LED3_G_config);

    gpio_pin_config_t LED3_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB18 (pin 41)  */
    GPIO_PinInit(BOARD_LED3_B_GPIO, BOARD_LED3_B_PIN, &LED3_B_config);

    gpio_pin_config_t LED2_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB19 (pin 42)  */
    GPIO_PinInit(BOARD_LED2_R_GPIO, BOARD_LED2_R_PIN, &LED2_R_config);

    gpio_pin_config_t LED2_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC0 (pin 43)  */
    GPIO_PinInit(BOARD_LED2_G_GPIO, BOARD_LED2_G_PIN, &LED2_G_config);

    gpio_pin_config_t LED2_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC2 (pin 45)  */
    GPIO_PinInit(BOARD_LED2_B_GPIO, BOARD_LED2_B_PIN, &LED2_B_config);

    gpio_pin_config_t LED1_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC3 (pin 46)  */
    GPIO_PinInit(BOARD_LED1_R_GPIO, BOARD_LED1_R_PIN, &LED1_R_config);

    gpio_pin_config_t LED1_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin 49)  */
    GPIO_PinInit(BOARD_LED1_G_GPIO, BOARD_LED1_G_PIN, &LED1_G_config);

    gpio_pin_config_t LED1_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC5 (pin 50)  */
    GPIO_PinInit(BOARD_LED1_B_GPIO, BOARD_LED1_B_PIN, &LED1_B_config);

    gpio_pin_config_t SW1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC6 (pin 51)  */
    GPIO_PinInit(BOARD_SW1_GPIO, BOARD_SW1_PIN, &SW1_config);

    gpio_pin_config_t SW2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC7 (pin 52)  */
    GPIO_PinInit(BOARD_SW2_GPIO, BOARD_SW2_PIN, &SW2_config);

    gpio_pin_config_t SW3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC8 (pin 53)  */
    GPIO_PinInit(BOARD_SW3_GPIO, BOARD_SW3_PIN, &SW3_config);

    gpio_pin_config_t SW4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC9 (pin 54)  */
    GPIO_PinInit(BOARD_SW4_GPIO, BOARD_SW4_PIN, &SW4_config);

    /* PORTA1 (pin 23) is configured as UART0_RX */
    PORT_SetPinMux(PORTA, 1U, kPORT_MuxAlt2);

    /* PORTA12 (pin 28) is configured as PTA12 */
    PORT_SetPinMux(BOARD_SW6_PORT, BOARD_SW6_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA12 (pin 28): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_SW6_PORT, BOARD_SW6_PIN, kPORT_InterruptRisingEdge);

    /* PORTA13 (pin 29) is configured as PTA13 */
    PORT_SetPinMux(BOARD_SW7_PORT, BOARD_SW7_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA13 (pin 29): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_SW7_PORT, BOARD_SW7_PIN, kPORT_InterruptRisingEdge);

    /* PORTA19 (pin 33) is configured as PTA19 */
    PORT_SetPinMux(BOARD_SW8_PORT, BOARD_SW8_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA19 (pin 33): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_SW8_PORT, BOARD_SW8_PIN, kPORT_InterruptRisingEdge);

    /* PORTA2 (pin 24) is configured as UART0_TX */
    PORT_SetPinMux(PORTA, 2U, kPORT_MuxAlt2);

    /* PORTA5 (pin 27) is configured as PTA5 */
    PORT_SetPinMux(BOARD_SW5_PORT, BOARD_SW5_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA5 (pin 27): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_SW5_PORT, BOARD_SW5_PIN, kPORT_InterruptRisingEdge);

    /* PORTB0 (pin 35) is configured as PTB0 */
    PORT_SetPinMux(BOARD_LCD_D1_PORT, BOARD_LCD_D1_PIN, kPORT_MuxAsGpio);

    /* PORTB1 (pin 36) is configured as PTB1 */
    PORT_SetPinMux(BOARD_LCD_D0_PORT, BOARD_LCD_D0_PIN, kPORT_MuxAsGpio);

    /* PORTB16 (pin 39) is configured as PTB16 */
    PORT_SetPinMux(BOARD_LED3_R_PORT, BOARD_LED3_R_PIN, kPORT_MuxAsGpio);

    /* PORTB17 (pin 40) is configured as PTB17 */
    PORT_SetPinMux(BOARD_LED3_G_PORT, BOARD_LED3_G_PIN, kPORT_MuxAsGpio);

    /* PORTB18 (pin 41) is configured as PTB18 */
    PORT_SetPinMux(BOARD_LED3_B_PORT, BOARD_LED3_B_PIN, kPORT_MuxAsGpio);

    /* PORTB19 (pin 42) is configured as PTB19 */
    PORT_SetPinMux(BOARD_LED2_R_PORT, BOARD_LED2_R_PIN, kPORT_MuxAsGpio);

    /* PORTB2 (pin 37) is configured as PTB2 */
    PORT_SetPinMux(BOARD_LCD_DC_PORT, BOARD_LCD_DC_PIN, kPORT_MuxAsGpio);

    /* PORTB3 (pin 38) is configured as PTB3 */
    PORT_SetPinMux(BOARD_LCD_RST_PORT, BOARD_LCD_RST_PIN, kPORT_MuxAsGpio);

    /* PORTC0 (pin 43) is configured as PTC0 */
    PORT_SetPinMux(BOARD_LED2_G_PORT, BOARD_LED2_G_PIN, kPORT_MuxAsGpio);

    /* PORTC10 (pin 55) is configured as PTC10 */
    PORT_SetPinMux(BOARD_IO8_PORT, BOARD_IO8_PIN, kPORT_MuxAsGpio);

    /* PORTC11 (pin 56) is configured as PTC11 */
    PORT_SetPinMux(BOARD_IO9_PORT, BOARD_IO9_PIN, kPORT_MuxAsGpio);

    /* PORTC2 (pin 45) is configured as PTC2 */
    PORT_SetPinMux(BOARD_LED2_B_PORT, BOARD_LED2_B_PIN, kPORT_MuxAsGpio);

    /* PORTC3 (pin 46) is configured as PTC3 */
    PORT_SetPinMux(BOARD_LED1_R_PORT, BOARD_LED1_R_PIN, kPORT_MuxAsGpio);

    /* PORTC4 (pin 49) is configured as PTC4 */
    PORT_SetPinMux(BOARD_LED1_G_PORT, BOARD_LED1_G_PIN, kPORT_MuxAsGpio);

    /* PORTC5 (pin 50) is configured as PTC5 */
    PORT_SetPinMux(BOARD_LED1_B_PORT, BOARD_LED1_B_PIN, kPORT_MuxAsGpio);

    /* PORTC6 (pin 51) is configured as PTC6 */
    PORT_SetPinMux(BOARD_SW1_PORT, BOARD_SW1_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTC6 (pin 51): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_SW1_PORT, BOARD_SW1_PIN, kPORT_InterruptRisingEdge);

    /* PORTC7 (pin 52) is configured as PTC7 */
    PORT_SetPinMux(BOARD_SW2_PORT, BOARD_SW2_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTC7 (pin 52): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_SW2_PORT, BOARD_SW2_PIN, kPORT_InterruptRisingEdge);

    /* PORTC8 (pin 53) is configured as PTC8 */
    PORT_SetPinMux(BOARD_SW3_PORT, BOARD_SW3_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTC8 (pin 53): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_SW3_PORT, BOARD_SW3_PIN, kPORT_InterruptRisingEdge);

    /* PORTC9 (pin 54) is configured as PTC9 */
    PORT_SetPinMux(BOARD_SW4_PORT, BOARD_SW4_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTC9 (pin 54): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_SW4_PORT, BOARD_SW4_PIN, kPORT_InterruptRisingEdge);

    /* PORTD0 (pin 57) is configured as PTD0 */
    PORT_SetPinMux(BOARD_IO7_PORT, BOARD_IO7_PIN, kPORT_MuxAsGpio);

    /* PORTD1 (pin 58) is configured as PTD1 */
    PORT_SetPinMux(BOARD_IO6_PORT, BOARD_IO6_PIN, kPORT_MuxAsGpio);

    /* PORTD2 (pin 59) is configured as PTD2 */
    PORT_SetPinMux(BOARD_IO5_PORT, BOARD_IO5_PIN, kPORT_MuxAsGpio);

    /* PORTD3 (pin 60) is configured as PTD3 */
    PORT_SetPinMux(BOARD_IO4_PORT, BOARD_IO4_PIN, kPORT_MuxAsGpio);

    /* PORTD4 (pin 61) is configured as PTD4 */
    PORT_SetPinMux(BOARD_IO3_PORT, BOARD_IO3_PIN, kPORT_MuxAsGpio);

    /* PORTD5 (pin 62) is configured as PTD5 */
    PORT_SetPinMux(BOARD_IO2_PORT, BOARD_IO2_PIN, kPORT_MuxAsGpio);

    /* PORTD6 (pin 63) is configured as PTD6 */
    PORT_SetPinMux(BOARD_IO1_PORT, BOARD_IO1_PIN, kPORT_MuxAsGpio);

    /* PORTD7 (pin 64) is configured as PTD7 */
    PORT_SetPinMux(BOARD_IO0_PORT, BOARD_IO0_PIN, kPORT_MuxAsGpio);

    /* PORTE0 (pin 1) is configured as UART1_TX */
    PORT_SetPinMux(PORTE, 0U, kPORT_MuxAlt3);

    /* PORTE1 (pin 2) is configured as UART1_RX */
    PORT_SetPinMux(PORTE, 1U, kPORT_MuxAlt3);

    /* PORTE20 (pin 9) is configured as PTE20 */
    PORT_SetPinMux(BOARD_AD5_PORT, BOARD_AD5_PIN, kPORT_MuxAsGpio);

    /* PORTE21 (pin 10) is configured as PTE21 */
    PORT_SetPinMux(BOARD_AD4_PORT, BOARD_AD4_PIN, kPORT_MuxAsGpio);

    /* PORTE22 (pin 11) is configured as PTE22 */
    PORT_SetPinMux(BOARD_AD3_PORT, BOARD_AD3_PIN, kPORT_MuxAsGpio);

    /* PORTE23 (pin 12) is configured as PTE23 */
    PORT_SetPinMux(BOARD_AD2_PORT, BOARD_AD2_PIN, kPORT_MuxAsGpio);

    /* PORTE24 (pin 20) is configured as PTE24 */
    PORT_SetPinMux(BOARD_IO10_PORT, BOARD_IO10_PIN, kPORT_MuxAsGpio);

    /* PORTE25 (pin 21) is configured as PTE25 */
    PORT_SetPinMux(BOARD_IO11_PORT, BOARD_IO11_PIN, kPORT_MuxAsGpio);

    /* PORTE29 (pin 17) is configured as PTE29 */
    PORT_SetPinMux(BOARD_AD1_PORT, BOARD_AD1_PIN, kPORT_MuxAsGpio);

    /* PORTE30 (pin 18) is configured as PTE30 */
    PORT_SetPinMux(BOARD_AD0_PORT, BOARD_AD0_PIN, kPORT_MuxAsGpio);

    /* PORTE31 (pin 19) is configured as PTE31 */
    PORT_SetPinMux(BOARD_IO12_PORT, BOARD_IO12_PIN, kPORT_MuxAsGpio);

    SIM->SOPT5 =
        ((SIM->SOPT5 &
          /* Mask bits to zero which are setting */
          (~(SIM_SOPT5_UART0TXSRC_MASK | SIM_SOPT5_UART0RXSRC_MASK | SIM_SOPT5_UART1TXSRC_MASK | SIM_SOPT5_UART1RXSRC_MASK)))

         /* UART0 Transmit Data Source Select: UART0_TX pin. */
         | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX)

         /* UART0 Receive Data Source Select: UART_RX pin. */
         | SIM_SOPT5_UART0RXSRC(SOPT5_UART0RXSRC_UART_RX)

         /* UART1 Transmit Data Source Select: UART1_TX pin. */
         | SIM_SOPT5_UART1TXSRC(SOPT5_UART1TXSRC_UART_TX)

         /* UART1 Receive Data Source Select: UART1_RX pin. */
         | SIM_SOPT5_UART1RXSRC(SOPT5_UART1RXSRC_UART_RX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
